apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: default
  labels:
    app: python-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: python-app
