apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-operator-kube-p-prometheus
  namespace: monitoring
spec:
  serviceMonitorSelector:
    matchLabels:
      app: python-app
